version: "3.8"

services:
  db:
    image: postgres:17.5-alpine
    container_name: rice-and-beans-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rice-and-beans
      PGDATA: /docker/pg
    volumes:
      - ./volumes/pg:/docker/pg
