FROM node:24.13.1 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY docker/env.template.js /etc/nginx/env.template.js

COPY docker/40-generate-env.sh /docker-entrypoint.d/40-generate-env.sh

RUN chmod +x /docker-entrypoint.d/40-generate-env.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
