name: Build and push frontend-main image

on:
  push:
    branches: [main]
    paths:
      - "frontend-main/**"
      - ".github/workflows/frontend-main-image.yml"
  workflow_dispatch:

jobs:
  build:
    uses: necro-org/workflows/.github/workflows/docker-image.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image: rice-and-beans-frontend-main
      context: ./frontend-main
